# Generated by Django 4.2.30 on 2026-06-03 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hotel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, validators=[hotel.models.validate_by_phone], verbose_name='Телефон')),
                ('birth_date', models.DateField(validators=[hotel.models.validate_age_18], verbose_name='Дата рождения')),
                ('has_child', models.BooleanField(default=False, verbose_name='Есть ли ребенок')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Дополнительное удобство')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Комфортность (Люкс, Полулюкс, Обычный)')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Номер комнаты')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за сутки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Фото номера')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.roomcategory', verbose_name='Категория')),
                ('features', models.ManyToManyField(blank=True, to='hotel.feature', verbose_name='Удобства')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Серия и номер паспорта')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='hotel.client')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Итоговая цена')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.client', verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room', verbose_name='Номер')),
            ],
        ),
    ]
