# Generated by Django 4.2.30 on 2026-06-03 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий о клиенте'),
        ),
        migrations.AddField(
            model_name='client',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(verbose_name='Дата поселения (заезд)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(verbose_name='Дата освобождения (выезд)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Итоговая цена (Платеж)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт системы'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Вместимость (кол-во мест)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за сутки (BYN)'),
        ),
    ]
